### ISSUE TITLE
Route fix in documentation

### ISSUE THREAD

**Issue by ergec** [ezralazuardy/heimdall#11]
Hello,
On this page https://heimdall.ezralazuardy.com/documentation/implementation#set-up-the-route-1

Following route works if you don't use any segments
`$routes->get('rest/users', 'Rest/Users::getUsers');`

If you want to use segments it has to be like this. (backslash instead of forwarslash between Rest and Users)

`$routes->get('rest/(:segment)/users', 'Rest\Users::getUsers/$1');`

**Comment by ezralazuardy** [comment]
thanks for the suggesstion! its now implemented on https://heimdall.lazuardy.tech/implementation#set-up-the-route-1
