### ISSUE TITLE
Remove codeigniter4/framework requirement

### ISSUE THREAD

**Issue by gitHusband** [ezralazuardy/heimdall#18]
#### Describe the solution you'd like

Please can you remove the codeigniter4/framework requirement

I don't think it's necessary.

**Comment by mv-steven** [comment]
You could probably just use the OAuth2 server directly https://github.com/thephpleague/oauth2-server

Heimdall essentially just makes integrating with the oauth2 server a little easier than doing it yourself.

**Comment by ezralazuardy** [comment]
heimdall is meant to be implemented on Codeigniter 4+ only. if you want to adapt to another framework or a native PHP project, please implement https://github.com/thephpleague/oauth2-server by yourself, as @mv-steven suggessted.

thanks!

**Comment by devin-acquired** [comment]
> heimdall is meant to be implemented on Codeigniter 4+ only. if you want to adapt to another framework or a native PHP project, please implement https://github.com/thephpleague/oauth2-server by yourself, as @mv-steven suggessted.
> 
> thanks!

No, I mean the requirement in composer.

![image](https://github.com/ezralazuardy/heimdall/assets/162088440/c050f2b7-410a-44d8-8d97-279b06ecf87a)
