### ISSUE TITLE
EZRALAZUARDY.COM , seems domain is expired

### ISSUE THREAD

**Issue by Salman98** [ezralazuardy/heimdall#20]
Website not working , so i can't check documentation 

https://heimdall.ezralazuardy.com/documentation/implementation

![image](https://user-images.githubusercontent.com/14360952/195548158-aaf1e6b7-0294-4020-915b-fc123f0cd574.png)

**Comment by ergec** [comment]
@ezralazuardy hello Ezra, I really appreciate your work and understand that maintaining a website might cost. It would be great, if it's possible, share at least an offline version of the documentation. Thanks.

**Comment by Strange-Panda** [comment]
+1

**Comment by doelmi** [comment]
I found the docusaurus documentation, https://github.com/ezralazuardy/heimdall-documentation

**Comment by ergec** [comment]
You may use this service to view docusaurus documentation online (no need to install anything) https://stackblitz.com/github/ezralazuardy/heimdall-documentation?file=README.md

**Comment by ezralazuardy** [comment]
sorry for the late response. the documentation is now live on https://heimdall.lazuardy.tech.

<img width="1440" alt="image" src="https://github.com/ezralazuardy/heimdall/assets/24422019/5e12a98e-7988-4309-9eef-7216a2227a0f">
