### ISSUE TITLE
[bug] Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead

### ISSUE THREAD

**Issue by ergec** [ezralazuardy/heimdall#8]
Authorization code grant type throws `Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead` during token generation because of the changes in lcobucci/jwt:3.4

league/oauth2-server:8.1.1 and lcobucci/jwt:3.3.3 works fine.

**Steps to reproduce the behavior:**
composer require ezralazuardy/heimdall //which installs latest versions of league/oauth2-server version 8.2.4 which uses lcobucci/jwt:3.4.5
Use authorization code grant
Token generation step gives error

**Expected behavior**
Generated tokens

**Screenshots**
![image](https://user-images.githubusercontent.com/422056/111963775-8e604e80-8afc-11eb-8d90-40be033d3cc9.png)

**Comment by ezralazuardy** [comment]
[Heimdall v0.0.4](https://github.com/ezralazuardy/heimdall/releases/tag/v0.0.4) is now released to fix this issue. thanks for your contribution.
